source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXAlipaySDK_Example', :exclusive => true do
  pod 'BXAlipaySDK', :path => '../'
end

target 'BXAlipaySDK_Tests', :exclusive => true do
  pod 'BXAlipaySDK', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
