source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BXAlipaySDK_Example' do
  pod 'BXAlipaySDK', :path => '../'

  target 'BXAlipaySDK_Tests' do
    inherit! :search_paths
  end
end
